name: SEMVER

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - 'release/**'

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUST_BACKTRACE: full

jobs:
  semver:
    name: semver
    runs-on: ubuntu-latest
    steps:
      - # actions/checkout v7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Check semver
        # obi1kenobi/cargo-semver-checks-action v2
        uses: obi1kenobi/cargo-semver-checks-action@6b69fcf40e9b5fb17adeb57e4b6ecd020649a239
        with:
          package: positive
          feature-group: all-features
          rust-toolchain: stable
